name: Handle PyPI Publish triggers

# output_object="{\"name\": \"$name\", \"version\": \"$version\", \"archive_url\": \"$archive_url\"}"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the package'
        required: true
      version:
        description: 'Version of the package'
        required: true
      archive_url:
        description: 'URL to the archive of the package'
        required: true
      commit_branch:
        description: 'Branch to commit the changes to. Special word "auto" (default) will create a new branch and PR with the name "pypi-{github.run_id}"'
        required: false
        default: 'auto'
      archive_sha256:
        description: 'SHA256 of the archive'
        required: false



jobs:
    build-and-commit:
        runs-on: ubuntu-latest

        permissions:
          pull-requests: write
          contents: write

        steps:
        - name: handle Python Package Publish
          uses: bitovi/github-actions-publish-github-pypi-handler@main
          with:
            name: ${{ inputs.name }}
            version: ${{ inputs.version }}
            archive_url: ${{ inputs.archive_url }}
            commit_branch: ${{ inputs.commit_branch }}
            archive_sha256: ${{ inputs.archive_sha256 }}
            pypi_base_url: "https://bitovi.github.io/PyPI"

            