name: Publish GitHub Pages on main commit

on:
  push:
    branches:
    - main
    - initial-working
    paths:
    - 'pypi/**'
    - 'pypi/**/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
          pages: write      # to deploy to Pages
          id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}

        steps:
        - id: deployment
          name: deployment
          uses: bitovi/github-actions-static-pypi-to-github-pages@main